package cmd

import (
	"net/http"

	"github.com/labstack/echo/v4"
	"github.com/mcucu/mns-ecommerce/internal/handlers"
	"github.com/mcucu/mns-ecommerce/internal/payloads"
	echoSwagger "github.com/swaggo/echo-swagger"

	_ "github.com/mcucu/mns-ecommerce/doc" // docs is generated by Swag CLI, you have to import it.
)

// Router ...
// @title mns-ecommerce Service
// @version 1.0.0
// @description mns-ecommerce Service
//
// @contact.name   mcucu
// @contact.email  mhd.cucu@gmail.com
//
// @schemes https http
// @BasePath /
//
// @securityDefinitions.apikey  ApiStaticToken
// @in                          header
// @name                        X-API-Key
func Router(e *echo.Echo, opt handlers.Options) {
	var (
		orderHandler   = handlers.NewOrderHandler(opt)
		productHandler = handlers.NewProductHandler(opt)
	)

	// Routes
	e.GET("/", func(c echo.Context) error {
		return c.JSON(http.StatusOK, payloads.Response{
			Code:       http.StatusOK,
			Success:    true,
			Message:    "API is running",
			Data:       nil,
			Exceptions: nil,
		})
	})

	// Swagger
	e.GET("/swagger/*", echoSwagger.WrapHandler)

	// Add product routes here
	productRoutes := e.Group("products")
	productRoutes.GET("", productHandler.GetProducts)

	// Add order routes here
	orderRoutes := e.Group("orders")
	orderRoutes.POST("", orderHandler.CreateOrder)
}
